### PR TITLE
Provide an upgrade path for the module merge that happen in 4.0.0

### LINKED ISSUE #397: deprecate and move jwtoptions on 3.9
For 4.0 jpms work we merged 2 modules but there's a data object that was used in a wrong package. In 3.9 it should be the new home of this class and the old location deprecated.

### PR DESCRIPTION
**Pull request by pmlopes**
Provide an upgrade path for the module merge happening on 4.0.0
Fixes #397

### CODE REVIEW

**Comment by pmlopes** [comment]
@jponge can you verify this?

File: vertx-jwt/src/main/java/io/vertx/ext/jwt/JWTOptions.java [hunk 1]
```diff
@@ -3,160 +3,19 @@
...
-  private String algorithm = "HS256";
-  private JsonObject header = EMPTY;
-  private boolean noTimestamp;
-  private int expiresInSeconds;
-  private List<String> audience;
-  private String issuer;
-  private String subject;
-  private List<String> permissions;
+/**
+ * @deprecated In 4.0.0 this module will be merged with vertx-auth-common, for this reason this class should be found
```
Comment (jponge) [inline vertx-jwt/src/main/java/io/vertx/ext/jwt/JWTOptions.java:7]: I would replicate the notice also on the deprecated `JWTOptions` definition.

**Review by jponge — COMMENTED** [review]
Minor comment, LGTM otherwise.
